/**
 * @license
 * Copyright 2025 Qwen Team
 * SPDX-License-Identifier: Apache-2.0
 */

// ── Session axis (per-conversation) ────────────────────────────────
export {
  DaemonSessionProvider,
  useDaemonActions,
  useDaemonActiveTodoList,
  useDaemonConnection,
  useDaemonPendingPermissions,
  useDaemonPromptStatus,
  useDaemonSessionNotices,
  useDaemonStreamingState,
  useDaemonSession,
  useDaemonTranscriptBlocks,
  useDaemonTranscriptHistory,
  useDaemonTranscriptState,
  useDaemonTranscriptStore,
  useDaemonWorkspaceEventSignals,
  extractDaemonTodosFromToolBlock,
  hasDaemonActiveTodos,
  isDaemonSubAgentToolBlock,
  parseDaemonTodoItemsFromEntries,
  selectDaemonActiveTodoList,
  selectDaemonLatestTodoList,
  selectDaemonPendingPermissions,
  selectDaemonSubAgentToolBlocks,
  selectDaemonStreamingState,
  selectDaemonTodoLists,
  selectDaemonTranscriptStreamingState,
  isMissingSessionHttpStatus,
  toDaemonPromptContent,
} from './session/index.js';
export type {
  DaemonCommandInfo,
  DaemonConnectionState,
  DaemonConnectionStatus,
  DaemonModelInfo,
  DaemonNoticeCategory,
  DaemonNoticeOperation,
  DaemonNoticeSeverity,
  DaemonPromptImage,
  DaemonPromptStatus,
  DaemonSessionActions,
  DaemonSessionContextValue,
  DaemonSessionNotice,
  DaemonSessionProviderProps,
  DaemonTranscriptHistory,
  DaemonTokenUsage,
  DaemonTodoItem,
  DaemonTodoList,
  DaemonTodoPriority,
  DaemonTodoStatus,
  DaemonStreamingState,
  DaemonWorkspaceEventSignals,
  PendingPromptActionOptions,
  SendPromptOptions,
  SubmitPromptOptions,
  SubmitPromptResult,
} from './session/index.js';

// ── Workspace axis (per-workspace, outlives sessions) ──────────────
export {
  DaemonWorkspaceProvider,
  useDaemonWorkspace,
  useDaemonWorkspaceActions,
  useOptionalDaemonWorkspace,
  useDaemonAgents,
  useDaemonAuth,
  useDaemonDiagnostics,
  useDaemonFiles,
  useDaemonGlob,
  useDaemonMcp,
  useDaemonMemory,
  useDaemonResource,
  useDaemonSessions,
  useDaemonSkills,
  useDaemonStatusReport,
  useDaemonUsageDashboard,
  useDaemonTools,
  useDaemonSettings,
  useDaemonProviders,
} from './workspace/index.js';
export type {
  DaemonDirectoryEntry,
  DaemonDirectoryListing,
  DaemonFileStat,
  DaemonGlobOptions,
  DaemonGlobResult,
  DaemonScheduledTask,
  DaemonScheduledTaskRun,
  DaemonCreateScheduledTaskRequest,
  DaemonUpdateScheduledTaskRequest,
  DaemonResourceOptions,
  DaemonStatusReportOptions,
  DaemonUsageDashboardOptions,
  DaemonWorkspaceActions,
  DaemonWorkspaceContextValue,
  DaemonWorkspaceProviderProps,
  DaemonWorkspaceStatus,
  ResourceResult,
  ResourceState,
} from './workspace/index.js';

export {
  useDaemonFollowupSuggestion,
  type UseDaemonFollowupSuggestionReturn,
} from './useDaemonFollowupSuggestion.js';

export { useDaemonMidTurnInjected } from './useDaemonMidTurnInjected.js';

export {
  getPendingPromptVersion,
  getPendingPromptEvents,
  consumePendingPromptEvents,
  subscribePendingPromptEvents,
  subscribePendingPromptVersion,
} from './pendingPromptVersion.js';

// ── Re-exported SDK types/constants for UI consumers ──────────────
// These allow web-shell and other UI packages to depend only on
// @qwen-code/webui without importing @qwen-code/sdk/daemon directly.
export { DAEMON_APPROVAL_MODES } from '@qwen-code/sdk/daemon';
export type {
  DaemonApprovalMode,
  DaemonStartInMode,
  DaemonAuthProviderBaseUrlOption,
  DaemonAuthProviderCatalog,
  DaemonAuthProviderDescriptor,
  DaemonAuthProviderInstallRequest,
  DaemonAuthProviderInstallResult,
  DaemonAuthProviderModel,
  DaemonContextCategoryBreakdown,
  DaemonContextFileScope,
  DaemonContextMemoryDetail,
  DaemonContextSkillDetail,
  DaemonContextToolDetail,
  DaemonSessionContextUsage,
  DaemonSessionContextUsageStatus,
  DaemonSessionStatsModelMetrics,
  DaemonSessionStatsStatus,
  DaemonSessionStatsToolByName,
  DaemonSessionSummary,
  DaemonUsageRange,
  DaemonUsageDashboard,
  DaemonUsageDashboardTotals,
  DaemonUsageModelShare,
  DaemonUsageSkillCall,
  DaemonUsageDailyPoint,
  DaemonUsageHeatmapDay,
  DaemonStatusReport,
  DaemonStatusReportDetail,
  DaemonStatusReportIssue,
  DaemonStatusReportLevel,
  DaemonStatusReportSection,
  DaemonStatusReportSession,
  DaemonMetricsSeriesBucket,
  DaemonWorkspaceAgentDetail,
  DaemonWorkspaceAgentSummary,
  DaemonWorkspaceMcpServerStatus,
  DaemonWorkspaceMcpToolStatus,
  DaemonWorkspaceMcpToolsStatus,
  DaemonWorkspaceMcpResourceStatus,
  DaemonWorkspaceMcpResourcesStatus,
  DaemonWorkspaceMemoryFile,
  DaemonWorkspaceSkillStatus,
  DaemonWorkspaceToolStatus,
  DaemonSettingDescriptor,
  DaemonWorkspaceSettingsStatus,
  DaemonSettingUpdateResult,
  DaemonWorkspaceProvidersStatus,
  DaemonWorkspaceProviderStatus,
  DaemonWorkspaceProviderModel,
  DaemonWorkspaceProviderCurrent,
  DaemonModelDeleteRequest,
  DaemonModelDeleteResult,
} from '@qwen-code/sdk/daemon';
