import type { DaemonSessionSummary } from '@qwen-code/sdk/daemon';

// Mirrors `SCHEDULED_TASK_RUN_SOURCE_ID_PREFIX` in
// acp-bridge/session-source.ts. The client cannot import that package.
const SCHEDULED_TASK_RUN_SOURCE_ID_PREFIX = 'scheduled_task_run:';
// Mirrors the time suffix appended by scheduledTaskRunSessionName in
// cli/src/runtime/scheduled-task-run.ts; change both together.
// Known limit: a user rename ending in this same shape is indistinguishable
// from a generated run name here, so it is classified as generated (outranks
// other renames, suffix stripped). Carrying the task title structurally —
// persisted alongside the run — would remove the guesswork.
const SCHEDULED_TASK_RUN_TIME_SUFFIX = / · \d{2}-\d{2} \d{2}:\d{2}$/u;

export interface ScheduledTaskSessionGroupIdentity {
  id: string;
  label: string;
}

export interface ScheduledTaskSessionSection {
  id: string;
  label: string;
  sessions: DaemonSessionSummary[];
}

function hasGeneratedRunName(session: DaemonSessionSummary): boolean {
  const displayName = session.displayName?.trim();
  return Boolean(
    displayName && SCHEDULED_TASK_RUN_TIME_SUFFIX.test(displayName),
  );
}

export function getScheduledTaskSessionGroup(
  session: DaemonSessionSummary,
): ScheduledTaskSessionGroupIdentity | undefined {
  if (session.sourceType !== 'default') return undefined;
  const sourceId = session.sourceId;
  if (!sourceId?.startsWith(SCHEDULED_TASK_RUN_SOURCE_ID_PREFIX)) {
    return undefined;
  }
  const taskId = sourceId.slice(SCHEDULED_TASK_RUN_SOURCE_ID_PREFIX.length);
  if (!taskId) return undefined;
  const displayName = session.displayName?.trim();
  // The label recovers the task title from the run display name generated by
  // scheduledTaskRunSessionName (cli/src/runtime/scheduled-task-run.ts),
  // which caps the title at MAX_RUN_SESSION_NAME_LENGTH: long or unnamed
  // tasks keep the producer's truncation and its trailing `…` here.
  const label = displayName?.replace(SCHEDULED_TASK_RUN_TIME_SUFFIX, '').trim();
  return {
    id: `scheduled-task:${taskId}`,
    label: label || taskId,
  };
}

export function collectScheduledTaskSession(
  sections: Map<string, ScheduledTaskSessionSection>,
  session: DaemonSessionSummary,
): boolean {
  const group = getScheduledTaskSessionGroup(session);
  if (!group) return false;
  const section = sections.get(group.id);
  if (section) {
    // Prefer the task title carried by a generated display name over a user
    // rename: runs are renameable, so first-wins would let the header flip
    // between the title and a rename whenever the catalog order shifts
    // (pinned rows sort first, the org-disabled path re-sorts by creation).
    if (
      hasGeneratedRunName(session) &&
      !section.sessions.some(hasGeneratedRunName)
    ) {
      section.label = group.label;
    }
    section.sessions.push(session);
  } else {
    sections.set(group.id, { ...group, sessions: [session] });
  }
  return true;
}
